name: CI
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: 'Install neovim'
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable
          sudo apt-fast update -qq
          sudo apt-fast install --no-install-recommends -yq neovim
      - name: 'Run check'
        run: make check
